# POST http://localhost:3000/encodeMessage HTTP/1.1
# content-type: application/json

# {
#     "sellerAddress": "0xBCC367E4b172459d981F2dFa01fDE7F983eBedAd",
#     "originalContractAddress": "0xD6344c3aC9f5e083B3a4BBAe763125bb5DE46D56",
#     "price": "1000000000000",
#     "tokenId": "0",
#     "tradeMarketAddress": "0x5639b7872e6Ff9fe61Bb8d08f72D95B24DF42D72"
# }

POST http://localhost:3000/marketplace/magicword HTTP/1.1
content-type: application/json

{
    "contract_address": "0xded83C0319Ae5e0d4d87031DdF54B9B6f494F98a",
    "token_id": 12
}